# Generated by Django 4.0.4 on 2022-12-05 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'not paid'), (1, 'paid')], default=0),
        ),
    ]
