# Generated by Django 4.0.4 on 2022-11-21 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deposit',
            old_name='transfer',
            new_name='wallet',
        ),
        migrations.RenameField(
            model_name='withdraw',
            old_name='transfer',
            new_name='wallet',
        ),
    ]
