# Generated by Django 4.0.4 on 2022-12-05 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cart_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='is_paid',
        ),
        migrations.AlterField(
            model_name='cart',
            name='payment_status',
            field=models.CharField(choices=[(0, 'پرداخت نشده'), (1, 'آنلاین'), (2, 'نقدی')], default=1, help_text='choose one of the method for payment!', max_length=10),
        ),
    ]
