# Generated by Django 4.0.4 on 2022-12-05 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_cart_is_paid_alter_cart_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='payment_status',
            field=models.CharField(choices=[('NOT_PAID', 'پرداخت نشده'), ('ONLINE', 'آنلاین'), ('CASH', 'نقدی')], default='پرداخت نشده', help_text='choose one of the method for payment!', max_length=32),
        ),
    ]
