# Generated by Django 4.0.4 on 2022-12-05 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_cart_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_paid',
            field=models.SmallIntegerField(default=False),
        ),
    ]
