# Generated by Django 4.0.4 on 2022-12-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_cart_is_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='is_paid',
        ),
        migrations.AlterField(
            model_name='cart',
            name='payment_status',
            field=models.CharField(choices=[('NOT_PAID', 'پرداخت نشده'), ('ONLINE', 'آنلاین'), ('CASH', 'نقدی')], default='NOT_PAID', help_text='choose one of the method for payment!', max_length=32),
        ),
    ]
