# Generated by Django 4.0.4 on 2022-12-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_remove_cart_is_paid_alter_cart_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_paid',
            field=models.SmallIntegerField(choices=[(0, 'پرداخت نشده'), (1, 'پرداخت شده ')], default=0),
        ),
    ]
