# Generated by Django 4.0.4 on 2022-12-01 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_alter_cart_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='payment',
            field=models.CharField(choices=[(1, 'نقدی'), (2, 'آنلاین'), (3, 'کیف پول ')], default=2, help_text='choose one of the method for payment!', max_length=10),
        ),
    ]
